// ============================================================
// GAME DATA
// ============================================================

const VENUES = [
  {
    id: 'mainframe',
    name: 'Mainframe Basement',
    policy: 'Easy',
    policyClass: 'policy-easy',
    music: 'Deep House',
    bpm: 122,
    dressCode: 'Dark Minimal',
    dressBias: ['Dark Minimal', 'No Logo'],
    locked: false,
    entryPrice: 10,
    desc: 'Underground vibes, low ceilings, warm crowd',
  },
  {
    id: 'compliance',
    name: 'The Compliance Vault',
    policy: 'Moderate',
    policyClass: 'policy-moderate',
    music: 'Techno',
    bpm: 136,
    dressCode: 'All Black, No Logos',
    dressBias: ['All Black', 'No Logo', 'Dark Minimal'],
    locked: false,
    entryPrice: 15,
    desc: 'Relentless techno, pitch-black interior, attitude required',
  },
  {
    id: 'neon',
    name: 'Neon Pharmacy',
    policy: 'Moderate',
    policyClass: 'policy-moderate',
    music: 'Drum & Bass',
    bpm: 174,
    dressCode: 'Streetwear / Eccentric',
    dressBias: ['Streetwear', 'Eccentric', 'Bright Colors'],
    locked: false,
    entryPrice: 12,
    desc: 'Colorful chaos, fast beats, anything-goes energy',
  },
  {
    id: 'boardroom',
    name: 'The Boardroom Penthouse',
    policy: 'Ruthless',
    policyClass: 'policy-ruthless',
    music: 'Tech-House',
    bpm: 128,
    dressCode: 'Smart Casual, Watches',
    dressBias: ['Smart Casual', 'Designer'],
    locked: true,
    entryPrice: 25,
  },
  {
    id: 'florians',
    name: "Florian's Private Members",
    policy: 'Ruthless',
    policyClass: 'policy-ruthless',
    music: 'Minimal Techno',
    bpm: 132,
    dressCode: 'Invite-Only Aura',
    dressBias: ['Understated', 'Dark Minimal'],
    locked: true,
    entryPrice: 30,
  },
  {
    id: 'audit',
    name: 'The Audit Chamber',
    policy: 'Nightmare',
    policyClass: 'policy-nightmare',
    music: 'Industrial',
    bpm: 145,
    dressCode: 'Full Uniform or Nothing',
    dressBias: ['All Black', 'Chains'],
    locked: true,
    entryPrice: 40,
  },
  {
    id: 'sisyphos',
    name: 'Sisyphos',
    policy: 'Easy',
    policyClass: 'policy-easy',
    music: 'Deep House',
    bpm: 120,
    dressCode: 'Anything Goes',
    dressBias: [],
    locked: false,
    entryPrice: 8,
    vibeCheck: true,
    desc: 'Open-air chaos, 48-hour parties, come as you are',
  },
  {
    id: 'sudpol',
    name: 'Südpol',
    policy: 'Moderate',
    policyClass: 'policy-moderate',
    music: 'Techno',
    bpm: 130,
    dressCode: 'Vibe Over Fashion',
    dressBias: [],
    locked: false,
    entryPrice: 10,
    vibeCheck: true,
    desc: 'The bouncer reads your energy, not your outfit',
  },
];

const CONTACTS = [
  {
    id: 'kai',
    name: 'Kai',
    initials: 'K',
    color: '#57f2ff',
    trait: 'Hype Engine',
    traitDesc: 'Queue +15% faster, anxiety +20% faster',
    traitColor: 'rgba(87, 242, 255, 0.15)',
    traitBorder: 'rgba(87, 242, 255, 0.3)',
    traitTextColor: '#57f2ff',
    styles: ['Dark Minimal', 'Chains', 'No Logo'],
    musicPref: 'Deep House',
    anxiety: 6,
    flakeRate: 15,
    portraitProps: { skin: '#c68642', hairColor: '#1a1a2e', hairStyle: 'short', shirtColor: '#0d1b2a', accessory: null, faceWidth: 7, faceHeight: 8, eyeSpacing: 4, noseSize: 1, earSize: 1, seed: 0.42 },
    flakeMsg: "YOOO I just got to the afters already, skip the queue lol",
    confirmMsg: "let's goooo, omw",
  },
  {
    id: 'pia',
    name: 'Pia',
    initials: 'P',
    color: '#ff4d6d',
    trait: 'Connected Promoter',
    traitDesc: 'Bouncer difficulty -1 tier, 40% flake',
    traitColor: 'rgba(255, 77, 109, 0.15)',
    traitBorder: 'rgba(255, 77, 109, 0.3)',
    traitTextColor: '#ff4d6d',
    styles: ['Smart Casual', 'Designer'],
    musicPref: 'Tech-House',
    anxiety: 5,
    flakeRate: 40,
    portraitProps: { skin: '#f5d0a9', hairColor: '#3d2b1f', hairStyle: 'long', shirtColor: '#ff4d6d', accessory: null, faceWidth: 6, faceHeight: 7, eyeSpacing: 3, noseSize: 1, earSize: 1, seed: 0.18 },
    flakeMsg: "babe the promoter just called, I'm going to another thing sorryyy",
    confirmMsg: "Yesss I'll be there in 20",
  },
  {
    id: 'rissal',
    name: 'Rissal',
    initials: 'R',
    color: '#39ff14',
    trait: 'The Chill Coder',
    traitDesc: 'Starts with gum + lighter, anxiety 9/10',
    traitColor: 'rgba(57, 255, 20, 0.15)',
    traitBorder: 'rgba(57, 255, 20, 0.3)',
    traitTextColor: '#39ff14',
    styles: ['Minimal', 'No Logo', 'Dark'],
    musicPref: 'Techno',
    anxiety: 9,
    flakeRate: 5,
    startsWithItems: ['gum', 'lighter'],
    portraitProps: { skin: '#8d5524', hairColor: '#2d2d2d', hairStyle: 'buzz', shirtColor: '#1b4332', accessory: 'glasses', faceWidth: 7, faceHeight: 8, eyeSpacing: 4, noseSize: 2, earSize: 1, seed: 0.65 },
    flakeMsg: "deploy broke prod, can't come",
    confirmMsg: "k. omw.",
  },
  {
    id: 'mona',
    name: 'Mona',
    initials: 'M',
    color: '#7b75ff',
    trait: 'The Fashionista',
    traitDesc: '2x Style Match, refuses Easy venues',
    traitColor: 'rgba(123, 117, 255, 0.15)',
    traitBorder: 'rgba(123, 117, 255, 0.3)',
    traitTextColor: '#7b75ff',
    styles: ['Eccentric', 'Vintage', 'Bold'],
    musicPref: 'Drum & Bass',
    anxiety: 4,
    flakeRate: 20,
    refusesEasy: true,
    portraitProps: { skin: '#f0c5a0', hairColor: '#d14070', hairStyle: 'bob', shirtColor: '#7b75ff', accessory: 'earring', faceWidth: 6, faceHeight: 7, eyeSpacing: 3, noseSize: 1, earSize: 1, seed: 0.82 },
    flakeMsg: "I just saw what everyone's wearing on insta. hard pass.",
    confirmMsg: "Outfit ready. I'll be iconic tonight.",
  },
  {
    id: 'sasha',
    name: 'Sasha',
    initials: 'S',
    color: '#fd9927',
    trait: 'Chaos Agent',
    traitDesc: 'Bonus random events in queue (good or bad)',
    traitColor: 'rgba(253, 153, 39, 0.15)',
    traitBorder: 'rgba(253, 153, 39, 0.3)',
    traitTextColor: '#fd9927',
    styles: ['Streetwear', 'Bright Colors'],
    musicPref: 'Drum & Bass',
    anxiety: 7,
    flakeRate: 25,
    portraitProps: { skin: '#dba270', hairColor: '#e84a5f', hairStyle: 'curly', shirtColor: '#ff6b35', accessory: 'piercing', faceWidth: 7, faceHeight: 7, eyeSpacing: 4, noseSize: 1, earSize: 1, seed: 0.37 },
    flakeMsg: "LMAOOO I'm already in the wrong part of town, my uber went rogue",
    confirmMsg: "BRO I JUST DID SOMETHING CRAZY but I'm coming",
  },
  {
    id: 'felix',
    name: 'Felix',
    initials: 'F',
    color: '#ffd86b',
    trait: 'The Insider',
    traitDesc: 'Starts with 1 free Intel revealed',
    traitColor: 'rgba(255, 216, 107, 0.15)',
    traitBorder: 'rgba(255, 216, 107, 0.3)',
    traitTextColor: '#ffd86b',
    styles: ['Smart Casual', 'Understated'],
    musicPref: 'Minimal Techno',
    anxiety: 6,
    flakeRate: 30,
    portraitProps: { skin: '#e8b88a', hairColor: '#c4931a', hairStyle: 'ponytail', shirtColor: '#2d2d2d', accessory: null, faceWidth: 6, faceHeight: 8, eyeSpacing: 3, noseSize: 1, earSize: 1, seed: 0.55 },
    flakeMsg: "yo my connect just hit me up, I'm going to a different spot. next time",
    confirmMsg: "Already got some info on tonight's door. See you there.",
  },
  {
    id: 'zara',
    name: 'Zara',
    initials: 'Z',
    color: '#ff69b4',
    trait: 'The Photographer',
    traitDesc: 'Documents everything — +reputation on success',
    traitColor: 'rgba(255, 105, 180, 0.15)',
    traitBorder: 'rgba(255, 105, 180, 0.3)',
    traitTextColor: '#ff69b4',
    styles: ['Eccentric', 'Vintage', 'Bold'],
    musicPref: 'Deep House',
    anxiety: 5,
    flakeRate: 20,
    unlockCondition: 'rep5',
    portraitProps: { skin: '#6b3e26', hairColor: '#1a1a2e', hairStyle: 'afro', shirtColor: '#e84a5f', accessory: null, faceWidth: 6, faceHeight: 7, eyeSpacing: 3, noseSize: 1, earSize: 1, seed: 0.72 },
    flakeMsg: "Can't tonight, editing photos from last weekend",
    confirmMsg: "Camera charged, outfit ready. Let's make content.",
  },
  {
    id: 'dex',
    name: 'Dex',
    initials: 'D',
    color: '#00ff88',
    trait: 'The Dealer',
    traitDesc: 'Starts with a random substance, knows everyone',
    traitColor: 'rgba(0, 255, 136, 0.15)',
    traitBorder: 'rgba(0, 255, 136, 0.3)',
    traitTextColor: '#00ff88',
    styles: ['Streetwear', 'Dark', 'No Logo'],
    musicPref: 'Techno',
    anxiety: 8,
    flakeRate: 35,
    unlockCondition: 'venue_compliance',
    portraitProps: { skin: '#c68642', hairColor: '#2d2d2d', hairStyle: 'short', shirtColor: '#1a1a2e', accessory: 'sunglasses', faceWidth: 7, faceHeight: 8, eyeSpacing: 4, noseSize: 2, earSize: 1, seed: 0.91 },
    flakeMsg: "heat outside tonight bro, laying low",
    confirmMsg: "I got the goods. See you outside. Don't be late.",
  },
  {
    id: 'yuki',
    name: 'Yuki',
    initials: 'Y',
    color: '#e0aaff',
    trait: 'The Diplomat',
    traitDesc: 'Calms arguments, -anxiety for whole squad',
    traitColor: 'rgba(224, 170, 255, 0.15)',
    traitBorder: 'rgba(224, 170, 255, 0.3)',
    traitTextColor: '#e0aaff',
    styles: ['Smart Casual', 'Understated', 'Minimal'],
    musicPref: 'Minimal Techno',
    anxiety: 7,
    flakeRate: 15,
    unlockCondition: 'rep10',
    portraitProps: { skin: '#fce0c5', hairColor: '#1a1a2e', hairStyle: 'bun', shirtColor: '#e0aaff', accessory: null, faceWidth: 6, faceHeight: 7, eyeSpacing: 3, noseSize: 1, earSize: 1, seed: 0.28 },
    flakeMsg: "Mediating a friend situation tonight, rain check",
    confirmMsg: "I'll keep everyone calm. On my way.",
  },
  {
    id: 'niko',
    name: 'Niko',
    initials: 'N',
    color: '#ff6b35',
    trait: 'The Local Legend',
    traitDesc: 'Bouncers know him — +15 starting approval',
    traitColor: 'rgba(255, 107, 53, 0.15)',
    traitBorder: 'rgba(255, 107, 53, 0.3)',
    traitTextColor: '#ff6b35',
    styles: ['Dark Minimal', 'Chains', 'All Black'],
    musicPref: 'Industrial',
    anxiety: 9,
    flakeRate: 10,
    unlockCondition: 'venue_boardroom',
    portraitProps: { skin: '#dba270', hairColor: '#1a1a2e', hairStyle: 'mohawk', shirtColor: '#1a1a2e', accessory: 'earring', faceWidth: 8, faceHeight: 8, eyeSpacing: 4, noseSize: 2, earSize: 2, seed: 0.63 },
    flakeMsg: "Already inside a different club lol. Come find me tmr",
    confirmMsg: "The bouncers know me. We're golden. 🤙",
  },
  {
    id: 'priya',
    name: 'Priya',
    initials: 'PR',
    color: '#ffc300',
    trait: 'The Networker',
    traitDesc: 'Unlocks contacts faster, +bond gains',
    traitColor: 'rgba(255, 195, 0, 0.15)',
    traitBorder: 'rgba(255, 195, 0, 0.3)',
    traitTextColor: '#ffc300',
    styles: ['Smart Casual', 'Designer', 'Bold'],
    musicPref: 'Tech-House',
    anxiety: 4,
    flakeRate: 25,
    unlockCondition: 'rep15',
    portraitProps: { skin: '#8d5524', hairColor: '#3d2b1f', hairStyle: 'long', shirtColor: '#ffc300', accessory: 'glasses', faceWidth: 6, faceHeight: 7, eyeSpacing: 3, noseSize: 1, earSize: 1, seed: 0.45 },
    flakeMsg: "At a networking event that's running late, next time!",
    confirmMsg: "I know like 5 people inside already. Let's GO.",
  },
  {
    id: 'ghost',
    name: 'Ghost',
    initials: 'G',
    color: '#888',
    trait: 'The Shadow',
    traitDesc: 'Invisible to bouncers — doesn\'t count as group',
    traitColor: 'rgba(136, 136, 136, 0.15)',
    traitBorder: 'rgba(136, 136, 136, 0.3)',
    traitTextColor: '#888',
    styles: ['Dark Minimal', 'No Logo', 'Understated'],
    musicPref: 'Minimal Techno',
    anxiety: 10,
    flakeRate: 5,
    unlockCondition: 'venue_florians',
    portraitProps: { skin: '#f5d0a9', hairColor: '#2d2d2d', hairStyle: 'bald', shirtColor: '#111', accessory: null, faceWidth: 6, faceHeight: 8, eyeSpacing: 3, noseSize: 1, earSize: 1, seed: 0.99 },
    flakeMsg: "...",
    confirmMsg: ".",
  },
  {
    id: 'jasper',
    name: 'Jasper',
    initials: 'J',
    color: '#00e5ff',
    trait: 'The Algorithm',
    traitDesc: 'Predicts queue movement — reduces wait time variance',
    traitColor: 'rgba(0, 229, 255, 0.15)',
    traitBorder: 'rgba(0, 229, 255, 0.3)',
    traitTextColor: '#00e5ff',
    styles: ['Minimal', 'No Logo', 'Streetwear'],
    musicPref: 'Deep House',
    anxiety: 8,
    flakeRate: 20,
    unlockCondition: 'rep5',
    portraitProps: { skin: '#f0c5a0', hairColor: '#e8d44d', hairStyle: 'short', shirtColor: '#0d1b2a', accessory: null, faceWidth: 7, faceHeight: 8, eyeSpacing: 4, noseSize: 1, earSize: 1, eyeColor: '#4a90d9', seed: 0.47 },
    flakeMsg: "training run just converged at 3AM, can't leave now sorry",
    confirmMsg: "I modeled the queue dynamics. Optimal arrival: now. omw.",
  },
];

const ITEMS = [
  { id: 'gum', name: 'Gum', icon: 'gum', iconColor: '#a4ff80', price: 5, desc: 'Low-value barter item, everybody wants one' },
  { id: 'lighter', name: 'Lighter', icon: 'fire', iconColor: '#fd9927', price: 10, desc: 'Medium barter value, classic ice-breaker' },
  { id: 'earplugs', name: 'Earplugs', icon: 'ear', iconColor: '#57f2ff', price: 12, desc: 'Reduces anxiety gain from loud events' },
  { id: 'water', name: 'Water Bottle', icon: 'drop', iconColor: '#57f2ff', price: 15, desc: "High barter value — it's 2 AM and everyone is dehydrated" },
  { id: 'vip', name: 'Fake VIP Wristband', icon: 'band', iconColor: '#ffd86b', price: 25, desc: 'Expensive & risky — can boost or backfire at bouncer' },
];

